import { loadEnv } from "../crawlers/env";
loadEnv();
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { supabaseAdmin } from "../../lib/supabase";

// detected_changes.review_status='pending' 목록을 모아 draft PR 자동 생성.
// GitHub Actions 안에서 실행. GH_TOKEN 필요.

function sh(cmd: string): string {
  return execSync(cmd, { encoding: "utf8", stdio: ["pipe", "pipe", "pipe"] }).trim();
}

async function main() {
  const s = supabaseAdmin();
  const { data: pending } = await s
    .from("detected_changes")
    .select("id, country_code, change_type, detected_at, diff_summary, regulation_source_id, source_document_id")
    .eq("review_status", "pending")
    .order("detected_at", { ascending: false })
    .limit(50);

  const list = pending ?? [];
  if (list.length === 0) {
    console.log("pending 없음 — draft PR 생성 스킵");
    return;
  }

  const date = new Date().toISOString().slice(0, 10);
  const branch = `auto/detected-changes-${date}`;

  // 이미 같은 날짜 브랜치 있으면 skip (중복 생성 방지)
  try {
    sh(`git ls-remote --exit-code origin ${branch}`);
    console.log(`브랜치 ${branch} 이미 존재 — skip`);
    return;
  } catch {
    // 없음 — 계속
  }

  const body = [
    `## 자동 감지된 법령 변경 ${list.length}건 (${date})`,
    "",
    "| 국가 | 유형 | 감지일 | 요약 |",
    "| --- | --- | --- | --- |",
    ...list.map((r) => {
      const sum = String(r.diff_summary ?? "").replaceAll("|", "\\|").slice(0, 80);
      const d = new Date(r.detected_at as string).toISOString().slice(0, 16).replace("T", " ");
      return `| ${r.country_code} | ${r.change_type} | ${d} | ${sum} |`;
    }),
    "",
    "## 처리 체크리스트",
    "",
    "- [ ] 각 항목의 원본 확인",
    "- [ ] `npm run parse` 실 실행해 Gemini로 재파싱 (변경된 문서만)",
    "- [ ] regulations 변경점 검토 (git diff)",
    "- [ ] 승인 시 `update detected_changes set review_status='approved', reviewed_by=...`",
    "- [ ] merge 시 promote 스크립트가 regulations 시간축 전환",
    "",
    "🤖 auto-generated by `.github/workflows/detect-changes-pr.yml`",
  ].join("\n");

  const bodyPath = ".pr-body.md";
  writeFileSync(bodyPath, body, "utf8");

  sh(`git checkout -b ${branch}`);
  // body 파일을 커밋 아티팩트로 추가 (변경 타임스탬프)
  sh(`echo "${date}: ${list.length} pending events" >> .auto-detect-log.md`);
  sh(`git add .auto-detect-log.md`);
  sh(`git -c user.email=bot@cosmetics-reg.dev -c user.name=detect-bot commit -m "auto: ${list.length} pending detected_changes (${date})"`);
  sh(`git push origin ${branch}`);

  // draft PR 생성
  sh(`gh pr create --draft --base main --head ${branch} --title "[auto] ${list.length} detected_changes (${date})" --body-file ${bodyPath}`);
  console.log(`✓ draft PR 생성: ${branch}`);
}

main().catch((e) => {
  console.error("open-draft-pr 실패:", e);
  process.exit(1);
});
